quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=opet290999
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkus

quarkus.hibernate-orm.database.generation=validate

quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=false

quarkus.hibernate-orm.log.sql=true
quarkus.http.port=8080

%docker.quarkus.datasource.db-kind=postgresql
%docker.quarkus.datasource.username=postgres
%docker.quarkus.datasource.password=password
%docker.quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/quarkus

%docker.quarkus.hibernate-orm.database.generation=validate
%docker.quarkus.flyway.migrate-at-start=true

quarkus.smallrye-openapi.path=/openapi

quarkus.swagger-ui.always-include=true

quarkus.swagger-ui.path=/swagger